### ISSUE TITLE
Navigation Timeout Exceeded

### ISSUE THREAD

**Issue by DennisRieg** [steinsag/hosteurope-letsencrypt#15]
Hi,

ich nutze schon länger das Skript und bin echt begeistet davon.

Ich untersuche gerade folgenden Fehler, den ich  heute reproduzierbar bekomme.

`
Traceback (most recent call last):
  File "set_certificate.py", line 72, in <module>
    asyncio.get_event_loop().run_until_complete(set_certificate())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "set_certificate.py", line 47, in set_certificate
    await page.goto('https://kis.hosteurope.de', {'waitUntil': 'networkidle2'})
  File "/usr/local/lib/python3.7/site-packages/pyppeteer/page.py", line 885, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.
`

Wenn ich ein wget https://kis.hosteurope.de mache, wird die Index Seite heruntergeladen. Hat jemand eine Idee, hat Hosteurope evtl. die Startseite verändert?

Viele Grüße und vielen Dank im Voraus
Gruß
Dennis

**Comment by DennisRieg** [comment]
Hallo,
ich habe das Skript nochtmal gestartet. Heute funktioniert es bei mir. Ich habe kein reboot oder sonstiges gemacht, nur nochmal neu gestartet. 
Vielen Dank für die tollen Skripte, ich schließe dieses Ticket wieder. 
Viele Grüße
Dennis

**Comment by Dennis650** [comment]
Hallo zusammen,

nächste Runde, selbes Problem.

```Traceback (most recent call last):
  File "set_certificate.py", line 72, in <module>
    asyncio.get_event_loop().run_until_complete(set_certificate())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "set_certificate.py", line 47, in set_certificate
    await page.goto('https://kis.hosteurope.de', {'waitUntil': 'networkidle2'})
  File "/usr/local/lib/python3.7/site-packages/pyppeteer/page.py", line 885, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.```

Hat das noch jemand beobachtet? Letztes Mal ging es 2 Täger später ohne Reboot oder irgendwelchen Änderungen.

Kann ich was außerhalb des Skriptes testen, um das Problem nachzustellen?

Ein wget von https://kis.hosteurope.de lädt sofort ohne Verzögerung die index.html herunter und ein ping kis.hosteurope.de liefert auch niedrige Antwortzeiten.

Vielen Dank im Voraus und Gruß
Dennis

**Comment by steinsag** [comment]
Ok, wir lassen diesen Issue zu und versuchen in deinem neuen Ticket #16 eine Lösung zu finden.
