### ISSUE TITLE
Navigation Timeout Exceeded: 30000 ms exceeded

### ISSUE THREAD

**Issue by Dennis650** [steinsag/hosteurope-letsencrypt#16]
Hallo zusammen,

nächste Runde, selbes Problem.

Ich hatte beim letzten Mal schon dieselben Probleme: https://github.com/steinsag/hosteurope-letsencrypt/issues/15

  File "set_certificate.py", line 72, in <module>
    asyncio.get_event_loop().run_until_complete(set_certificate())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "set_certificate.py", line 47, in set_certificate
    await page.goto('https://kis.hosteurope.de', {'waitUntil': 'networkidle2'})
  File "/usr/local/lib/python3.7/site-packages/pyppeteer/page.py", line 885, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.```

Hat das noch jemand beobachtet? Letztes Mal ging es 2 Täger später ohne Reboot oder irgendwelchen Änderungen.

Kann ich was außerhalb des Skriptes testen, um das Problem nachzustellen?

Ein wget von https://kis.hosteurope.de lädt sofort ohne Verzögerung die index.html herunter und ein ping kis.hosteurope.de liefert auch niedrige Antwortzeiten.

Vielen Dank im Voraus und Gruß
Dennis

**Comment by steinsag** [comment]
Kannst du mal probieren, in Zeile 47 die URL zu ändern in:

    https://sso.hosteurope.de/?app=kis&path=%2F

Vielleicht liegt es ja an dem Redirect, den Hosteurope neuerdings macht.

**Comment by Dennis650** [comment]
Hi,

erstmal Danke für Deine Hilfe. Auch mit der neuen URL direkt auf dies sso Seite klappt es nicht. Wenn ich eine Seite von mir im Internet angebe, läuft das Skript weiter und findet dann natürlich die entsprechenden Login-Felder nicht. ich wollte nur ausprobieren, ob generell connections klappen.

```
Traceback (most recent call last):
  File "set_certificate.py", line 72, in <module>
    asyncio.get_event_loop().run_until_complete(set_certificate())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "set_certificate.py", line 47, in set_certificate
    await page.goto('https://sso.hosteurope.de/?app=kis&path=%2F', {'waitUntil': 'networkidle2'})
  File "/usr/local/lib/python3.7/site-packages/pyppeteer/page.py", line 885, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.
```

Viele Grüße
Dennis

**Comment by Dennis650** [comment]
Hi,

habe das ganze noch auf meinem RasperryPI analysiert. Hatte Timeouts hochgesetzt usw... Sehr wahrscheinlich hatte der Chromium-Browser aber einfach nicht genügend Speicher zur Verfügung. Ich habe alle Anwendungen auf meinen PI beendet und das Skript nochmal ausgeführt. Jetzt läuft es durch :-) Werde beobachten...

Vielen Dank und Gruß
Dennis
