### ISSUE TITLE
certbot not available and not installable

### ISSUE THREAD

**Issue by MRigal** [steinsag/hosteurope-letsencrypt#20]
Hi @steinsag and thanks for the good job.
It might be a version difference, but on our Dedicated WebServer based on Debian Buster, I have no `certbot` command available from the shell and also no way to install it, also not through pip as I can't create virtual environments.
Any thoughts?
Cheers, Matthieu

**Comment by steinsag** [comment]
Those scripts are only helpful for so called webpacks. Those are not servers, but old style of Webspace.

So not sure how to do it in your case. I assume you would install certbot on your private machine. But not sure if you can upload stuff to your server via FTP and assign a certificate via KIS to your server.

**Comment by MRigal** [comment]
Thanks @steinsag ! I misunderstood that. 

FYI, on the WebServers, one need to use the getssl shell utility, similarly to https://github.com/mklemme1/hosteurope-letsencrypt
