### ISSUE TITLE
FTP permission denied nach Umzug auf neuen Rechner

### ISSUE THREAD

**Issue by OliverWieland** [steinsag/hosteurope-letsencrypt#21]
Ich habe das Skript auf einen neuen Rechner übertragen. Auch das Verzeichnis ~/.config/hosteurope-letsencrypt wurde auf den neuen Recner kopiert.
Wenn ich jetzt das verlaengern.py-Skript ausführe, bekomme ich folgende Meldung:

> Hook '--manual-auth-hook' for <MY_DOMAIN> reported error code 1
> Hook '--manual-auth-hook' for <MY_DOMAIN> ran with error output:
>  Traceback (most recent call last):
>    File "/home/oli/Tools/hosteurope-letsencrypt/validate.py", line 58, in <module>
>      ftp.storbinary('STOR %s' % filename, temp)
>    File "/usr/lib/python3.10/ftplib.py", line 498, in storbinary
>      with self.transfercmd(cmd, rest) as conn:
>    File "/usr/lib/python3.10/ftplib.py", line 393, in transfercmd
>      return self.ntransfercmd(cmd, rest)[0]
>    File "/usr/lib/python3.10/ftplib.py", line 793, in ntransfercmd
>      conn, size = super().ntransfercmd(cmd, rest)
>    File "/usr/lib/python3.10/ftplib.py", line 359, in ntransfercmd
>      resp = self.sendcmd(cmd)
>    File "/usr/lib/python3.10/ftplib.py", line 281, in sendcmd
>      return self.getresp()
>    File "/usr/lib/python3.10/ftplib.py", line 254, in getresp
>      raise error_perm(resp)
>  ftplib.error_perm: 550 UORSfRDTd-YPjei5tgcqvoFxSLVJl_RZR5-sJ0RPkJw: Permission denied
> 
> Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems:
>   Domain: <MY_DOMAIN>
>   Type:   unauthorized
>   Detail: 2a01:488:42:1000:50ed:849b:2c:7805: Invalid response from http://<MY_DOMAIN>/.well-known/acme-challenge/UORSfRDTd-YPjei5tgcqvoFxSLVJl_RZR5-sJ0RPkJw: 404
> 

Die FTP-Credentials in der Datei ftp.json wurden überprüft, die stimmen.
Was läuft schief?

**Comment by steinsag** [comment]
Das sieht für mich danach aus, dass der FTP Nutzer keine Schreibrechte auf dem FTP Server hat. Das Skript versucht hier ja eine Datei hochzuladen.

**Comment by OliverWieland** [comment]
Ja, Du hast recht... Da hab ich wohl parallel an den Berechtigungen gebastelt... :-|
Danke für den Tritt in die richtige Richtung... ;-)
