### ISSUE TITLE
set_certificate.py - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Dennis650** [steinsag/hosteurope-letsencrypt#8]
Hallo zusammen,

erstmal vielen Dank für Eure tolle Arbeit 👍 

Ich versuche gerade das neue Feature mit dem automatischem Upload der generierten Zertifikate zu nutzen.

Auf menem RaspberryPI 3B habe ich gerade eine frischen Installation von hosteurope-letsencrypt gemacht. Die Zertifikate wurden wie gewohnt generiert.

Ich bekomme es allerdings nicht hin die Zertifikate hochzuladen. Ich vermute es liegt an meiner Python Installation, allerdings finde ich keine Lösung.
pyppeteer habe ich mit "pip3 install pyppeteer" installiert. Scheinbar ist das aber mit meiner Python Version (3.5.3) nicht kompatibel!? 

`/usr/bin/python3 set_certificate.py `
führt zu:

> Traceback (most recent call last):
>   File "set_certificate.py", line 6, in <module>
>     from pyppeteer import launch
>   File "/usr/local/lib/python3.5/dist-packages/pyppeteer/__init__.py", line 30, in <module>
>     from pyppeteer.launcher import connect, launch, executablePath  # noqa: E402
>   File "/usr/local/lib/python3.5/dist-packages/pyppeteer/launcher.py", line 75
>     self.url = f'http://127.0.0.1:{self.port}'
>                                              ^
> SyntaxError: invalid syntax

Habt ihr Hinweise für mich, wonach ich suchen kann / achten sollte?

Vielen Dank und Gruß
Dennis

**Comment by steinsag** [comment]
Ich würde es mit einem virtualenv probieren. Im README steht auch kurz, wie das prinzipiell geht. Virtualenv kannst du per Paketmanager deiner Distro installieren. Danach:

    virtualenv env --python=python3
    source env/bin/activate
    pip install pyppeteer

Ansonsten fällt noch auf, dass du Python 3.5 hast. Das ist ja eine Version, die nicht mehr gepflegt wird und auch eine erste Version der Python 3 Serie war. Laut https://pypi.org/project/pyppeteer/ ist pypeteer nicht mit Python 3.5 kompatibel. Vielleicht liegt es auch einfach daran.

**Comment by Dennis650** [comment]
Hi,

vielen Dank! Ich habe nun eine neuere Python Version lokal gebaut. 

Dann musste ich noch ein 2 Hürden nehmen. pyppeteer lädt bei der ersten Benutzung ein chrome herunter. Leider auf dem RasperryPI in einer x64 Version. Das habe ich mittels Symlink auf einen chrome für einen PI gelöst.
Dann musste ich im set_certificate.py Skript noch headless auf True setzen, da mein PI Headless läuft. Dann hat es geklappt!!
Vielen Dank und Gruß
Dennis

**Comment by steinsag** [comment]
Danke für die Rückmeldung! Damit haben wir den ersten positiven Bericht über den Zertifikat-Upload :-)
